### PR TITLE
Push TOC, landing page, edits to Live

### PR DESCRIPTION
**Pull request by cjgronlund**
Reviewed by Brad B and Carolyn

### CODE REVIEW

**Comment by cjgronlund** [comment]
Investigating broken links

**Comment by cjgronlund** [comment]
Please approve: @KittyYeungQ & @cgranade: Pushing fixes from master to live.
Landing page, TOC updates plus Q# user guide, key concepts, etc.

**Comment by KittyYeungQ** [comment]
I think it's good for the time being. Now that we have a Q# user guide, I'm wondering if it makes sens to move the Q# library under it later.

**Comment by cjgronlund** [comment]
Good thought, @KittyYeungQ. Brad and I did a click-through on the TOC and all articles, and there's definitely room for that kind of refinement.

**Pull request merged**
