### PR TITLE
Update what-is-quantum-computing.md

### PR DESCRIPTION
**Pull request by cjgronlund**
Replace paras per Cathy Palmer and Bettina Heim

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/overview/what-is-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/e7a05727a06a1e4baae87c091d2da0d8ad48c867/articles/overview/what-is-quantum-computing.md) | 84 | 66 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16803d0b-6751-42cc-a054-e6bd8f75ef45_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/overview/what-is-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/c9d7f3aa0d6a433770abc992e472c94adf348036/articles/overview/what-is-quantum-computing.md) | 84 | 66 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30f3775c-7ac4-4fed-a903-8bae4092a350_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/overview/what-is-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4533a9f11869154e7338a3a226f1b86844baf40f/articles/overview/what-is-quantum-computing.md) | 84 | 66 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/388c07ed-7acf-45f9-b24f-65afdcef4026_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by cjgronlund** [comment]
#sign-off

**Pull request merged**
