### PR TITLE
Changed png /media file links

### PR DESCRIPTION
**Pull request by v-stgr**
...from ~ to .. to correct build errors.

### CODE REVIEW

**Comment by v-stgr** [comment]
#sign-off

**Comment by v-stgr** [comment]
@bromeg

**Comment by v-stgr** [comment]
@cgrande can you please review and accept if the change looks okay?

**Comment by cgranade** [comment]
As with my comment on #508, I'd like to make sure this keeps with best practices on relative versus absolute paths before we merge it in.

**Comment by v-stgr** [comment]
OK. I will hold off on these PRs.  Thanks.

**Pull request closed without merging**
