### PR TITLE
Update microsoft.quantum.math.sqrt.yml

### PR DESCRIPTION
**Pull request by mridulsar**
Nothing too crazy. I tried changing type to Int and got error i was missing open bracket, doc was just a bit confusing

### CODE REVIEW

**Comment by geduardo** [comment]
Thanks for doing this! However, as is pointed out in the README of the repository:

> ⚠️ If you want to modify an article of the API reference, DO NOT modify the *.yml file in this repository, as any changes would be automatically overwritten in the next build. These files are automatically generated from the comments in the language source code files, which are located in the repositories Quantum Libraries and Q# runtime. To modify the article you should locate the original source file, apply the changes in the comments there, and submit the pull request to its respective repository. For more details, please see the documentation section of the contribution guide.

To modify this file you should go to the source code in the [Quantum Libraries repository](https://github.com/microsoft/quantumlibraries). However, I couldn't find the original source code file.

@cgranade, do you know where I can find the source code of this `.yml`? Apparantely is under Microsoft.quantum.extensions.math, but I couldn't find it searching through the libraries.

**Comment by Bradben** [comment]
> @cgranade, do you know where I can find the source code of this .yml? Apparantely is under Microsoft.quantum.extensions.math, but I couldn't find it searching through the libraries.

It's in \qsharp-runtime\src\Simulation\QsharpCore\Math

**Comment by geduardo** [comment]
Closing this PR since it's not the correct repository.

**Comment by cgranade** [comment]
> To modify this file you should go to the source code in the [Quantum Libraries repository](https://github.com/microsoft/quantumlibraries). However, I couldn't find the original source code file.
> 
> @cgranade, do you know where I can find the source code of this `.yml`? Apparantely is under Microsoft.quantum.extensions.math, but I couldn't find it searching through the libraries.

To add to @Bradben's answer, the old `Microsoft.Quantum.Extensions.Math` namespace was deprecated with Q# 0.6, such that the QuantumLibraries repo used to contain deprecation stubs that call from that old namespace to the new functions and operations in the `Microsoft.Quantum.Math` namespace. Those stubs have now been removed in accordance with [our API design principles](https://docs.microsoft.com/quantum/contributing/api-design-principles), since it has been longer than six months since the deprecation.

As an implementation details, some parts of the Q# standard libraries are defined in the qsharp-runtime repo as @Bradben notes; this is due to the order in which dependencies are built, and is not generally a user-facing change except when contributing to documentation or code.

**Pull request closed without merging**
