### PR TITLE
Update Quantum doc landing page

### PR DESCRIPTION
**Pull request by cjgronlund**
Per new style

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/2ad6e38e792648141f27542c81ef30b56bcc6929/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c10f74bd-bed5-41c8-98d8-904eae159a75_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4228604b2a48657b724e4102dc43752a014cb3c6/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d012f83c-b160-4a38-b5c2-8c9b126dda48_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4228604b2a48657b724e4102dc43752a014cb3c6/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eadaab7e-7452-410a-8077-acdc4eb9880c_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4228604b2a48657b724e4102dc43752a014cb3c6/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac5283b9-e5bc-4e3d-a3fe-f5532c1c9275_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/735494e7cca0833bb9a4eded97e03a805927a17b/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d65222e1-903f-4f29-907e-e6e5fb423d07_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/735494e7cca0833bb9a4eded97e03a805927a17b/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa219e26-daf2-4959-a49c-40c0868b5dc1_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/735494e7cca0833bb9a4eded97e03a805927a17b/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66eba235-b152-4bce-bc9c-61a82572e694_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/c7db276014052c1351785bb16085aeea01a94a65/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06556cbd-157f-40fa-b65e-c3dcab85d992_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/c7db276014052c1351785bb16085aeea01a94a65/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c9d6961-5206-45c5-b749-2b2817aa2c90_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/c7db276014052c1351785bb16085aeea01a94a65/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9f61084-40e8-4cb5-9082-82f48ff74dfc_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1f5be6fb51a7c3b92dd169144a8f37b16645b8ac/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ba4fc82-9e60-4b36-a281-23e52245a09f_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1f5be6fb51a7c3b92dd169144a8f37b16645b8ac/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13dd62e9-3a66-4325-8443-f8853b8f3fc8_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1f5be6fb51a7c3b92dd169144a8f37b16645b8ac/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6f05ce3-de78-4eaf-82c0-913072d82271_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f568e112ba202ae78ee1c54da10034f59f33408a/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/585e448b-d34b-4ec5-902a-1245a950f943_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f568e112ba202ae78ee1c54da10034f59f33408a/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e848093-b9b8-48da-9d9f-82a2a466d979_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f568e112ba202ae78ee1c54da10034f59f33408a/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/041d1868-9e57-4057-8d2f-173214164c63_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/96beac47ab91b82cf0f85af724a4a4789c03d51a/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60b91abf-599a-4ad1-8690-0ced0d153bd5_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/96beac47ab91b82cf0f85af724a4a4789c03d51a/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a25099bd-a2ee-4e1b-8135-8b33911d20b4_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/96beac47ab91b82cf0f85af724a4a4789c03d51a/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f74432a-55bb-4a6e-be77-0f5509cfaee0_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/b49fe2b152222672ea65217bf6cf22152404eae3/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2cfa143-a063-4adf-ad0c-2bc98f36bffa_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/b49fe2b152222672ea65217bf6cf22152404eae3/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15c7d2b6-6248-4e00-87a4-bf35add9a3b3_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/b49fe2b152222672ea65217bf6cf22152404eae3/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f228a9ae-f551-41c4-8c1e-0930aff0316d_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by cjgronlund** [comment]
@natke  - please review landing page. Thanks!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d5b43dfdd7f8f40a8d297b9d707f917920e216bb/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62fbd438-c012-49d3-80a3-ea81c5746e13_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d5b43dfdd7f8f40a8d297b9d707f917920e216bb/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8567dff5-423a-4d04-9e54-355d4c372d4c_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d5b43dfdd7f8f40a8d297b9d707f917920e216bb/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b303481-a671-4951-9e9c-7a1c37584128_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/44d19b9e8076c6dd421aa38c402679f549e24343/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/146272b3-8788-4558-aa9d-2d0d15c5e73a_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/44d19b9e8076c6dd421aa38c402679f549e24343/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d0e2d7e-c80e-4e55-9e96-3dcb5d28b836_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/44d19b9e8076c6dd421aa38c402679f549e24343/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2671a756-9d7b-4bbd-a4fe-004a31c69c44_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by cjgronlund** [comment]
@natke - please review
We need to check the box for conversion; then, we can refine as the doc story is refined.
#sign-off

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/7e422ec1cf3fc3cd4f81fd43b485e022825b1ce3/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5edca90b-17dc-4688-a268-f164573bc645_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/7e422ec1cf3fc3cd4f81fd43b485e022825b1ce3/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16d4b3fa-cf83-4ae4-a7f3-8475914dd291_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/7e422ec1cf3fc3cd4f81fd43b485e022825b1ce3/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dab864b5-9c31-4885-a9c0-c04462527087_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/TOC.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/0ebb20dd9614849ebb7f5b9876fb05b7a00d24f3/articles/TOC.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c82d2db-125b-4bec-a737-5f74d0ea7f83_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/index.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/0ebb20dd9614849ebb7f5b9876fb05b7a00d24f3/articles/index.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/111a405a-72cb-4e72-8437-429ad0c7e507_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/welcome.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/0ebb20dd9614849ebb7f5b9876fb05b7a00d24f3/articles/welcome.md) | 85 | 72 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e54efc9-8dcd-4ac5-948d-1b93a7a1bddc_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by cjgronlund** [comment]
@natke 
Requested changes made. #sign-off
Please approve

**Pull request merged**
