### PR TITLE
Updated VS Code create/run project instructions

### PR DESCRIPTION
**Pull request by gillenhaalb**
First two address Issue #610, and the third is simply for ease of access:

- added **Select 'standalone console application'** step when creating new project
- replaced error filled "Run Without Debugging" step with `dotnet run` terminal workaround
- added anchor links to mirror the "Create a Q# Project" page

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/how-to-guides/create-qsharp-project.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/8672165a74ae823e8a22476a05e282d7ad6d24fb/articles/how-to-guides/create-qsharp-project.md) | 92 | 75 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d76e5a35-3826-4316-a6a1-bc6ab2dac693_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/8672165a74ae823e8a22476a05e282d7ad6d24fb/articles/install-guide/index.md) | 96 | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af98f953-6c66-40bc-92cd-01b475c2f809_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/8672165a74ae823e8a22476a05e282d7ad6d24fb/articles/install-guide/update.md) | 87 | 74 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbe01767-2ed9-4fef-bae2-3bc85ab5f171_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/how-to-guides/create-qsharp-project.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1511841f96138ef7d73f43cdb68cacb9d33ba99f/articles/how-to-guides/create-qsharp-project.md) | 92 | 72 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8eafb05e-0f73-4182-8bfb-2e448aec50d3_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1511841f96138ef7d73f43cdb68cacb9d33ba99f/articles/install-guide/index.md) | 90 | 81 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47d69782-f99e-488d-abf7-a71608be7771_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/how-to-guides/create-qsharp-project.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/606900204ec6927353f8c3fc1da1d8461b64e40f/articles/how-to-guides/create-qsharp-project.md) | 92 | 72 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad1ec9ac-b1bc-4833-9aea-181385853016_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/606900204ec6927353f8c3fc1da1d8461b64e40f/articles/install-guide/index.md) | 90 | 81 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d9dcab1-72d8-4808-8a8f-f8c5d23b4264_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/606900204ec6927353f8c3fc1da1d8461b64e40f/articles/install-guide/update.md) | 88 | 68 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3acd244-eeee-4057-8bb2-9067b2a39643_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by gillenhaalb** [comment]
Superseded by #615, #616, and #624, closing now

**Pull request closed without merging**
