### PR TITLE
re-title What Is article in concepts

### PR DESCRIPTION
**Pull request by cjgronlund**
Avoid duplication of titles with the What Is article in 5 things you need to know. Provide a more precise search intent.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/cbc05fc5a3df2aeb884f736a2924f3c3f4e89352/articles/concepts/index.md) | 75 | 52 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85cb7e2e-33dc-416c-8e5b-b3c336fcca7d_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/49cdb7f5dbe4468b0015bad6e23a1ee72a8420b0/articles/concepts/index.md) | 80 | 52 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c1940c2-559e-413e-8eb9-716f8fe6df78_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/39cb6bdecb19f94179845ee556072fc1f28c5b9e/articles/concepts/index.md) | 80 | 52 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/968fe820-f4ef-4507-ae00-0d5c4c9a77b2_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/concepts/toc.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/39cb6bdecb19f94179845ee556072fc1f28c5b9e/articles/concepts/toc.yml) | 87 | 24 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7aaba4f-2289-42e5-a1d9-cd4d31a00d00_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by cjgronlund** [comment]
#sign-off

**Pull request merged**
