### PR TITLE
Change link for "Next steps" in the installation guide (fix #821)

### LINKED ISSUE #821: "What's next?" links on the installation guide takes users to wrong tutorial
**Problem:** “What’s next?” link on the installation guide takes the user to “Quantum Basics with Q#” that is based on the use of host programs.
**Proposed solution:** Change the hyperlinks to refer to the QRNG tutorial.
**Comments:** There will be still some issues, e.g. QRNG doesn't explain how to run the application in Q# Jupyter Notebooks.

### PR DESCRIPTION
**Pull request by geduardo**
Things done in this PR:

- Change the link from "What's next?" in the installation guide from the "Exploring enganglement with Q#" to the QRNG.
- Remove "What's next?" section from the Update guide (it doesn't make sense to take people to the first tutorial in an update guide).

Fixes #821

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/16981b3fb28d6e66b0d7e1823c774185644afad1/articles/install-guide/csinstall.md) | 98 | 91 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cacc1131-0790-439e-9b97-ec13b7b1ffb7_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/pyinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/16981b3fb28d6e66b0d7e1823c774185644afad1/articles/install-guide/pyinstall.md) | 94 | 76 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86e318c8-11f8-4430-bb71-34eef847ab5d_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/16981b3fb28d6e66b0d7e1823c774185644afad1/articles/install-guide/qjupyter.md) | 86 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fec422e1-8342-44b0-a5af-d94254f6207d_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/16981b3fb28d6e66b0d7e1823c774185644afad1/articles/install-guide/standalone.md) | 88 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1b54ed9-913a-4cca-bedd-8f02a6850d9d_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/16981b3fb28d6e66b0d7e1823c774185644afad1/articles/install-guide/update.md) | 85 | 61 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cb2e4d8-2a2f-460f-aaa6-69281f5a4888_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by gillenhaalb** [comment]
Good call on the update guide, in hindsight that was quite odd. Two suggestions:
1. Perhaps a different "What's Next?" for the Jupyter install page? The instructions for the QRNG don't include the specifics for Jupyter.
2. Maybe this isn't the PR for it, but I think the tab titles could be pared down on the QRNG page (see pic below). It took me way longer than it should to determine which setups each tab corresponds to. I'd suggest maybe removing the "Visual Studio and Visual Studio Code" from each, and just adding a short sentence beforehand saying they apply for both IDEs. Also, for the Python instructions, could we simply trust that if they're using Python, they'll sort out how to run the file themselves? Besides the ".. or the command line" in the tab title (particularly confusing now that the command line application is right next to it), I'm nervous that telling them specifically to go with `python host.py` could lead to issues (e.g. maybe the path for `python`  isn't set to the right version, or if they simply open the terminal and don't execute it while in the same directory as the file.)


image

**Comment by geduardo** [comment]
Maybe we can create a Q# Notebook with the QRNG, add it to binder and link to it from there...
About the second thing, yeah, completely agree. I had exactly the same problem.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/29a73bf706630f2118d941cc8ec32f4bce10509a/articles/install-guide/csinstall.md) | 98 | 91 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10a43a5a-f902-442b-9959-a2097bc39504_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/pyinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/29a73bf706630f2118d941cc8ec32f4bce10509a/articles/install-guide/pyinstall.md) | 94 | 76 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1032fc2e-7ab7-4b67-8c5f-9725296193d5_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/29a73bf706630f2118d941cc8ec32f4bce10509a/articles/install-guide/qjupyter.md) | 86 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/845dac52-6401-46a6-a8dc-61a4a8d2e082_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/29a73bf706630f2118d941cc8ec32f4bce10509a/articles/install-guide/standalone.md) | 88 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20f88d2c-42b9-45c4-a8ff-184aefe67c22_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/29a73bf706630f2118d941cc8ec32f4bce10509a/articles/install-guide/update.md) | 85 | 61 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e15d87d1-ad14-45f0-ad0c-622cca5a04d1_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f0c56049922f3cb84ae5b7d90bbac5ccd7cae8b8/articles/install-guide/csinstall.md) | 98 | 91 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7624f65-27a7-4937-bba6-502bddd01c96_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/pyinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f0c56049922f3cb84ae5b7d90bbac5ccd7cae8b8/articles/install-guide/pyinstall.md) | 94 | 76 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99832adb-d8c8-44ba-b96d-54db7a5d7e64_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f0c56049922f3cb84ae5b7d90bbac5ccd7cae8b8/articles/install-guide/qjupyter.md) | 86 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/571cc765-2863-4620-ad76-a98a57409007_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f0c56049922f3cb84ae5b7d90bbac5ccd7cae8b8/articles/install-guide/standalone.md) | 88 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d2e0aff-5ffb-4497-b07d-9fa68689157e_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/f0c56049922f3cb84ae5b7d90bbac5ccd7cae8b8/articles/install-guide/update.md) | 85 | 61 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/289b3afb-94b6-4996-8780-882fb3d493dd_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/csinstall.md) | 98 | 91 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2e0ac2f-ccde-48b2-8140-2482694231b7_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/pyinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/pyinstall.md) | 94 | 76 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a118902-8086-4e8e-b95e-4cef52890f27_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/qjupyter.md) | 86 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ce9090c-dcd1-4125-b80f-aff54b69aac8_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/standalone.md) | 88 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a230d346-b0f6-4d83-91f2-a4938a789042_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/update.md) | 85 | 61 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a47c0c2-b9b7-4ac6-958b-115af8afb8a8_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/csinstall.md) | 98 | 91 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87cf38f7-0bf6-4401-b917-d466bedb48d4_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/pyinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/pyinstall.md) | 94 | 76 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8515e0b5-863a-4b02-970b-a42ffa3338e7_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/qjupyter.md) | 86 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b9eef40-1333-42f2-8130-f94c1ec51ab5_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/standalone.md) | 88 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02e477bf-a36b-4ada-9657-1e72774a04f0_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/71f4139dbfc1da76f153064b1f6885327dce9266/articles/install-guide/update.md) | 85 | 61 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81496d9e-a8f2-40ca-8b53-0abe8785f8cb_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/csinstall.md) | 98 | 91 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4d46f2a-bd15-4bd1-b67e-785730ba1734_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/pyinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/pyinstall.md) | 94 | 76 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db2722c0-42b1-454d-9ba4-d5b6ec84fcf1_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/qjupyter.md) | 86 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a5db844-ceb9-4344-97f0-23bc264a7d2b_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/standalone.md) | 88 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6821e120-2191-4a6d-96c6-7630a15eb183_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/update.md) | 85 | 61 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48fe762f-7669-41b1-a755-2f2f133cba1f_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by KittyYeungQ** [comment]
> Maybe we can create a Q# Notebook with the QRNG, add it to binder and link to it from there...
> About the second thing, yeah, completely agree. I had exactly the same problem.

**Comment by KittyYeungQ** [comment]
> Good call on the update guide, in hindsight that was quite odd. Two suggestions:
> 
> 1. Perhaps a different "What's Next?" for the Jupyter install page? The instructions for the QRNG don't include the specifics for Jupyter.
> 2. Maybe this isn't the PR for it, but I think the tab titles could be pared down on the QRNG page (see pic below). It took me way longer than it should to determine which setups each tab corresponds to. I'd suggest maybe removing the "Visual Studio and Visual Studio Code" from each, and just adding a short sentence beforehand saying they apply for both IDEs. Also, for the Python instructions, could we simply trust that if they're using Python, they'll sort out how to run the file themselves? Besides the ".. or the command line" in the tab title (particularly confusing now that the command line application is right next to it), I'm nervous that telling them specifically to go with `python host.py` could lead to issues (e.g. maybe the path for `python`  isn't set to the right version, or if they simply open the terminal and don't execute it while in the same directory as the file.)
> 
> image

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/csinstall.md) | 98 | 91 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f97c1980-429d-438d-b1e2-d6e72b1d6847_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/pyinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/pyinstall.md) | 94 | 76 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/657822aa-19da-4076-9954-974eb965e6f2_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/qjupyter.md) | 86 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/841915c5-0bdb-49ad-b7d9-f6f7a6b0574c_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/standalone.md) | 88 | 75 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4420d7c-b70c-43a4-8e99-d3e244aa3667_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/1d160b93bf3c53255328f88a74d196ea0c3e949b/articles/install-guide/update.md) | 85 | 61 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/778f417b-b5a3-427c-9cd3-79dbf37cc689_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by KittyYeungQ** [comment]
> Good call on the update guide, in hindsight that was quite odd. Two suggestions:
> 
> 1. Perhaps a different "What's Next?" for the Jupyter install page? The instructions for the QRNG don't include the specifics for Jupyter.
> 2. Maybe this isn't the PR for it, but I think the tab titles could be pared down on the QRNG page (see pic below). It took me way longer than it should to determine which setups each tab corresponds to. I'd suggest maybe removing the "Visual Studio and Visual Studio Code" from each, and just adding a short sentence beforehand saying they apply for both IDEs. Also, for the Python instructions, could we simply trust that if they're using Python, they'll sort out how to run the file themselves? Besides the ".. or the command line" in the tab title (particularly confusing now that the command line application is right next to it), I'm nervous that telling them specifically to go with `python host.py` could lead to issues (e.g. maybe the path for `python`  isn't set to the right version, or if they simply open the terminal and don't execute it while in the same directory as the file.)
> 
> image

This PR can be merged asap. For the tabs, I agree with reducing the many mentions of the IDEs. Also, we may move the python and C# options to their own page anyways. So this page should have just the Q# commend line tutorial. I don't get why we need to make another RNG tutorial for Notebook @geduardo Is it just to show all four options for the same tutorial?

**Comment by gillenhaalb** [comment]
> > Good call on the update guide, in hindsight that was quite odd. Two suggestions:
> > 
> > 1. Perhaps a different "What's Next?" for the Jupyter install page? The instructions for the QRNG don't include the specifics for Jupyter.
> > 2. Maybe this isn't the PR for it, but I think the tab titles could be pared down on the QRNG page (see pic below). It took me way longer than it should to determine which setups each tab corresponds to. I'd suggest maybe removing the "Visual Studio and Visual Studio Code" from each, and just adding a short sentence beforehand saying they apply for both IDEs. Also, for the Python instructions, could we simply trust that if they're using Python, they'll sort out how to run the file themselves? Besides the ".. or the command line" in the tab title (particularly confusing now that the command line application is right next to it), I'm nervous that telling them specifically to go with `python host.py` could lead to issues (e.g. maybe the path for `python`  isn't set to the right version, or if they simply open the terminal and don't execute it while in the same directory as the file.)
> > 
> > image
> 
> This PR can be merged asap. For the tabs, I agree with reducing the many mentions of the IDEs. Also, we may move the python and C# options to their own page anyways. So this page should have just the Q# commend line tutorial. I don't get why we need to make another RNG tutorial for Notebook @geduardo Is it just to show all four options for the same tutorial?

@KittyYeungQ I agree, don't think a whole new page is necessary. But it's currently odd to direct people who just installed Q# for Jupyter to this page, and then provide no information about how to do the QRNG in Jupyter. The specifics would be as simple as 
- giving the operation code block, 
- telling them to put it in a Jupyter cell and execute,
- telling them to execute `%simulate SampleRandomNumber` in another cell.

I'd suggest Jupyter share the fate of Python and C#, so in the interim (before the new page explaining the host program process gets made) I think either it should get its own tab here, or we don't link to it from the Jupyter install instructions. Similarly for C# and Python, if we remove the tabs here, we should probably remove the links sending people here from their respective install pages

**Comment by KittyYeungQ** [comment]
> > > Good call on the update guide, in hindsight that was quite odd. Two suggestions:
> > > 
> > > 1. Perhaps a different "What's Next?" for the Jupyter install page? The instructions for the QRNG don't include the specifics for Jupyter.
> > > 2. Maybe this isn't the PR for it, but I think the tab titles could be pared down on the QRNG page (see pic below). It took me way longer than it should to determine which setups each tab corresponds to. I'd suggest maybe removing the "Visual Studio and Visual Studio Code" from each, and just adding a short sentence beforehand saying they apply for both IDEs. Also, for the Python instructions, could we simply trust that if they're using Python, they'll sort out how to run the file themselves? Besides the ".. or the command line" in the tab title (particularly confusing now that the command line application is right next to it), I'm nervous that telling them specifically to go with `python host.py` could lead to issues (e.g. maybe the path for `python`  isn't set to the right version, or if they simply open the terminal and don't execute it while in the same directory as the file.)
> > > 
> > > image
> > 
> > 
> > This PR can be merged asap. For the tabs, I agree with reducing the many mentions of the IDEs. Also, we may move the python and C# options to their own page anyways. So this page should have just the Q# commend line tutorial. I don't get why we need to make another RNG tutorial for Notebook @geduardo Is it just to show all four options for the same tutorial?
> 
> @KittyYeungQ I agree, don't think a whole new page is necessary. But it's currently odd to direct people who just installed Q# for Jupyter to this page, and then provide no information about how to do the QRNG in Jupyter. The specifics would be as simple as
> 
> * giving the operation code block,
> * telling them to put it in a Jupyter cell and execute,
> * telling them to execute `%simulate SampleRandomNumber` in another cell.
> 
> I'd suggest Jupyter share the fate of Python and C#, so in the interim (before the new page explaining the host program process gets made) I think either it should get its own tab here, or we don't link to it from the Jupyter install instructions. Similarly for C# and Python, if we remove the tabs here, we should probably remove the links sending people here from their respective install pages

Got it. Let's direct people from the installation to the same experience in QRNG. I think we can group Jupyter, Pythong and C# into a new page for QRNG.

**Pull request merged**
