### PR TITLE
[DO NOT MERGE] Reference docs for 0.12.2010.16413.

### PR DESCRIPTION
**Pull request by cgranade**
This PR contains preview documentation generated using the new documentation generator introduced with https://github.com/microsoft/qsharp-compiler/pull/594/files. This PR is for preview purposes only, and should not be merged. If you notice any issues with the rendering, please let me know in comments so that I can address them in the documentation generation tool itself. Thank you!

### CODE REVIEW

**Comment by cgranade** [comment]
One note already: the toc.yml file generated by summarize_documentation.py is not correctly filtering namespaces, so each namespace contains all contents of all namespaces.... not ideal. It also looks like empty package links are not getting suppressed correctly.

**Comment by rmshaffer** [comment]
One "random" 🙄 comment:

See the `Microsoft.Quantum.Math.RandomInt` page in this PR:
https://review.docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.randomint?branch=pr-en-us-1084
image

vs. the same page from `main`:
https://review.docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.randomint?branch=main
image

With this PR's changes, there are a few differences that may potentially be issues:

- the "please use" link does not resolve correctly.
- the Q# block does not appear to have syntax highlighting (perhaps because the keyword `operation` is missing?)
- the `Input` and `Output` sections are missing (although maybe that's intentional for a deprecated operation?)

**Comment by cgranade** [comment]
> One "random" 🙄 comment:
> 
> See the `Microsoft.Quantum.Math.RandomInt` page in this PR:
> https://review.docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.randomint?branch=pr-en-us-1084
> image
> 
> vs. the same page from `main`:
> https://review.docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.randomint?branch=main
> image
> 
> With this PR's changes, there are a few differences that may potentially be issues:
> 
> * the "please use" link does not resolve correctly.
> * the Q# block does not appear to have syntax highlighting (perhaps because the keyword `operation` is missing?)
> * the `Input` and `Output` sections are missing (although maybe that's intentional for a deprecated operation?)

Thanks for pointing those out, @rmshaffer! I think I have some hypotheses about what's causing those, so I'll go on and take a look. Thanks again!

**Comment by geduardo** [comment]
I guess this one is outdated and can be closed. Please, reopen if not @cgranade .

**Pull request closed without merging**
