### PR TITLE
Update changes made before May 6 2020

### PR DESCRIPTION
**Pull request by KittyYeungQ**

### CODE REVIEW

**Comment by geduardo** [comment]
Apparently there's a conflict with the TOC file

**Comment by KittyYeungQ** [comment]
Open a new PR

**Comment by KittyYeungQ** [comment]
@cgranade we are observing something strange here. Not sure why the build failed. The TOC file was already merged from master to live but it's showing up again here. The only change after that was #813 we'd like to merge to live.

**Comment by cgranade** [comment]
Very odd indeed. There should never be conflicts between live and master by construction; I wonder if something went wrong with a previous merge to live, and just didn't happen to affect anything until modifying the same file again? Easy enough to fix, though; I can remove branch protection on master for a moment, merge live into master, push it back, then master will be strictly ahead of live.

(What I wouldn't give to be able to set merge policies per-branch instead of per-repo...)

**Comment by cgranade** [comment]
I'll get on that as soon as I can, apologies for the delay.

**Comment by KittyYeungQ** [comment]
Thank you very much @cgranade

**Comment by cgranade** [comment]
It should be fixed, please let me know if anything else happens.

**Pull request merged**
