### PR TITLE
Correcting images for dark mode visualization

### LINKED ISSUE #733: Circuit diagram not visible in Dark mode
Quantum Circuit diagram is not visible when theme is set to dark mode. #648 doesn't seems to solve it. Has that change been deployed?

image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0986a4c4-0a4e-85aa-f803-f9b058acf166
* Version Independent ID: 4a8b6844-9d32-8759-3b59-6558285e9f6f
* Content: [Applications in the Q# standard libraries - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/standard/applications#feedback)
* Content Source: [articles/libraries/standard/applications.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/standard/applications.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **martinro@microsoft.com**

### PR DESCRIPTION
**Pull request by geduardo**
In this PR:
- I modify .png and .svg files to add a white background. This is necessary for correct visualization in dark mode.
- I restore some .svg files that were changed to low-resolution .png files.
- I delete some unnecessary files.
- I add a README.md to the /media folder to warn about the use of transparent elements. Also brief tutorial of how to eliminate them.

This PR fixes #733

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/circuits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/88651db63d4ade26038bf0ba398b2623c0c97966/articles/concepts/circuits.md) | 79 | 57 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bef3c756-fdcd-45ca-9459-37f78139b441_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/circuits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/aefd6ff2c53ac14d3b8abd1d9b71dd6febe357ab/articles/concepts/circuits.md) | 79 | 57 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bdaccf2-0590-44b3-a08b-1686c9cf1650_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/circuits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/9c22b65a4c0052f1bf70759b276387f9b25a619c/articles/concepts/circuits.md) | 79 | 57 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f840c510-6799-4cf3-b924-7ee289670a82_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/media/README.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/9c22b65a4c0052f1bf70759b276387f9b25a619c/articles/media/README.md) | 77 | 25 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bcfe73f-dc12-43d7-bbe4-098085781435_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/circuits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/74753591a60555d68a7d3e7fb274d7b75e250cfa/articles/concepts/circuits.md) | 79 | 57 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/836da83c-3611-48c4-baf7-a9b1847c7a85_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/media/README.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/74753591a60555d68a7d3e7fb274d7b75e250cfa/articles/media/README.md) | 77 | 25 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/113b5daa-6a99-40e8-a93c-37ac3dfb461d_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/circuits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/42528593c42e7071d0af025e2d53665b94f1b067/articles/concepts/circuits.md) | 79 | 57 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d9322de-3e85-41d9-b2ce-4fdc45aaea6a_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/libraries/standard/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/42528593c42e7071d0af025e2d53665b94f1b067/articles/libraries/standard/algorithms.md) | 73 | 56 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a5b9533-6d71-4162-8f39-21a6e355dc41_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/media/README.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/42528593c42e7071d0af025e2d53665b94f1b067/articles/media/README.md) | 77 | 25 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b32383b-6e1b-46db-9a10-40e0eda51d6d_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/circuits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d399ff11775cbfde00029ce10ea6f67808addbb8/articles/concepts/circuits.md) | 79 | 57 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae4f282e-bbb8-48e2-9c6b-de717faf2005_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/libraries/standard/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d399ff11775cbfde00029ce10ea6f67808addbb8/articles/libraries/standard/algorithms.md) | 73 | 56 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14a29561-4b85-4016-912d-a94c0010b32c_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/media/README.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d399ff11775cbfde00029ce10ea6f67808addbb8/articles/media/README.md) | 78 | 26 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0490031-b465-436c-a8dd-812732b9e6ae_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/concepts/circuits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d399ff11775cbfde00029ce10ea6f67808addbb8/articles/concepts/circuits.md) | 79 | 57 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d781dad-3997-47d2-89ae-b71d0c373d77_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/libraries/standard/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d399ff11775cbfde00029ce10ea6f67808addbb8/articles/libraries/standard/algorithms.md) | 73 | 56 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ba59113-b0e4-4ac4-b625-61a3f3e90bab_report.html) | [:white_check_mark:](# "Successfully processed") |
| [articles/media/README.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/d399ff11775cbfde00029ce10ea6f67808addbb8/articles/media/README.md) | 78 | 26 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6503ea88-545b-4390-b26c-2384c6069eee_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by geduardo** [comment]
Other Microsoft teams have similar problems: https://github.com/MicrosoftDocs/azure-docs/issues/40037. I don't see an easy solution to this that doesn't include the clunky white background. They could invert the colors in dark mode, but that will likely lead to similar issues as well. Maybe we could round the corners of the white background to stylize it a bit. I don't know. Keep me informed :)

**Comment by geduardo** [comment]
Any update here @natke ?

**Comment by natke** [comment]
Yes, I do have an update - there is no solution to switch images based on the UI mode right now, so we should push these changes, and keep our eye on best practice for dark mode images.

**Pull request merged**
