### PR TITLE
Update IQ# magic commands quick reference page

### PR DESCRIPTION
**Pull request by rmshaffer**
Updating this page with the latest relevant content from the auto-generated page here:
https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/iqsharp-magic/index.md

The main benefit here is including links to the detailed documentation for each individual magic command.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/user-guide/quickref/iqsharp.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/a8d200c3525da1211de80b6d2efbac554fb7724b/articles/user-guide/quickref/iqsharp.md) | 94 | 74 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a750928e-21f9-4e0a-9e63-c78e26a01a53_report.html) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by gillenhaalb** [comment]
@rmshaffer Great idea, links are hugely helpful. When I went to review I noticed in the API that the new release included some new `%azure. ... ` magic commands. Would you want to go ahead and include those in this PR?

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/user-guide/quickref/iqsharp.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/dc69e68b5cae2717dd5d228e675a34101f7d3a52/articles/user-guide/quickref/iqsharp.md) | 91 | 56 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9af551de-b9e0-4ff7-a32c-9c5285c392f5) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by rmshaffer** [comment]
> When I went to review I noticed in the API that the new release included some new `%azure. ... ` magic commands. Would you want to go ahead and include those in this PR?

@gillenhaalb I think that makes sense; just added them. The commands are only useful for users who have access to the Azure Quantum preview, but that's fine (as you say, the API documentation is already published anyway).

**Pull request merged**
