### PR TITLE
Changed png /media file links

### PR DESCRIPTION
**Pull request by v-stgr**
...from ~ to .. to correct build errors.

### CODE REVIEW

**Comment by v-stgr** [comment]
@bromeg

**Comment by v-stgr** [comment]
@cgrande can you please review and accept if the change looks okay?

**Comment by cgranade** [comment]
My understanding from discussion with @natke on #493  was that `~` is preferred to `..` to avoid breaking links when reorganizing content. Should we be moving to relative paths instead?

**Comment by v-stgr** [comment]
Oh, I thought you had switched to .. instead of ~ because of build errors.

**Pull request closed without merging**
