### PR TITLE
Add quantum brand - attempt #2

### PR DESCRIPTION
**Pull request by cjgronlund**

### CODE REVIEW

**Comment by cgranade** [comment]
The title suffix doesn't seem to show up on the review site its under `globalMetadata`, but I tried putting it under `fileMetadata` instead and that seems to work:
```
"fileMetadata": {
      "titleSuffix": {
        "**/**.md": "Microsoft Quantum"
      },
      // MathJaX config here.
}
```

**Comment by cjgronlund** [comment]
@cgranade - Thanks for the heads up. The fileMetadata setting: Have you already tested this setting? I'm unable to see a preview build of the PR I submitted. But, I'm following this example: https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/docfx.json

**Comment by cgranade** [comment]
@cjgronlund: No worries, thanks for helping us get the title suffix working, I didn't even know there was such a setting until your first PR! It looks from the review rendering like the `fileMetadata` approach works, but not sure why it would be any different than `globalMetadata`...

**Comment by cjgronlund** [comment]
@cgranade Thanks for the heads up. I was having trouble seeing the staged version, so thanks for checking. I'll make the change and resubmit. Interesting how this is done different ways in different repos!

**Comment by cjgronlund** [comment]
@cgranade: I think this should do it. Thank you for your feedback. :>)

**Pull request merged**
