### PR TITLE
Update config to enable docfx v3

### PR DESCRIPTION
**Pull request by v-caxian**
[AB#249348](https://dev.azure.com/ceapex/Engineering/_workitems/edit/249348)

This Pull Request is for docfxv3 migration, after the Pull Request merged, the repository will be built with docfxv3 instead of docfxv2.

### CODE REVIEW

**Comment by geduardo** [comment]
There appear to be some warnings from lacking metadata. @rmshaffer do you know if these API files are automatically generated? I saw you modified them (https://github.com/MicrosoftDocs/quantum-docs-pr/commit/c06aff27da4c3a5e29688e9ff81968045080b369).

**Comment by cgranade** [comment]
> There appear to be some warnings from lacking metadata. @rmshaffer do you know if these API files are automatically generated? I saw you modified them ([c06aff2](https://github.com/MicrosoftDocs/quantum-docs-pr/commit/c06aff27da4c3a5e29688e9ff81968045080b369)).

I can confirm that these files are automatically generated, using the build script at https://github.com/microsoft/iqsharp/blob/master/build/docs/build_docs.py.

**Comment by geduardo** [comment]
I see, thanks. Do you know how can I find the source code originating the Markdown files, @cgranade ?

**Comment by cgranade** [comment]
The metadata is generated by that Python script, using the built-in documentation for each magic command. For instance, the `Documentation` object at https://github.com/microsoft/iqsharp/blob/master/src/Kernel/Magic/LsMagicMagic.cs#L36 is processed by the `build_docs.py` script to become the contents of `ls_magic.md`.

**Comment by geduardo** [comment]
I see, then we should modify this block (https://github.com/microsoft/iqsharp/blob/master/build/docs/build_docs.py#L197) to add the author and the correct format date, right?

**Comment by rmshaffer** [comment]
@geduardo I think that is correct, yes.

Also FYI, https://github.com/microsoft/iqsharp/issues/134 is tracking this.

**Comment by geduardo** [comment]
I started a PR to try to fix it here: https://github.com/microsoft/iqsharp/pull/210

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/resources/contributing/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/resources/contributing/index.md) | 86 | 62 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a5b4767-2487-469a-9161-7424842914e5) | [:white_check_mark:](# "Successfully processed") |
| [articles/resources/contributing/style-guide.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/resources/contributing/style-guide.md) | 81 | 56 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7899a69-9dbd-463c-833e-d155b9db778a) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/additional-libraries.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/additional-libraries.md) | 86 | 62 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54676875-8900-4b12-a386-07f7094a6326) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/chemistry/installation.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/chemistry/installation.md) | 80 | 51 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93fe7c6f-31e4-47dd-af5b-d3be740e7e60) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/index.md) | 76 | 51 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2bd2112-6bbf-44cd-8ef6-73379c117394) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/machine-learning/intro.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/machine-learning/intro.md) | 74 | 50 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cda25b31-0c05-4f3c-852b-a5f127b12a82) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/machine-learning/toc.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/machine-learning/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de91a7a2-e43e-41e6-bb92-6e058cc1fc7c) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/numerics/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/numerics/index.md) | 75 | 59 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9afb372-efb3-495d-bbfd-6e52fda63f7f) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/numerics/toc.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/numerics/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12799dc1-c44c-4bef-b506-99f265b3b613) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/standard/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/standard/algorithms.md) | 74 | 54 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b2d22df-3a01-4ba3-b16a-4b925b903317) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/standard/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/standard/index.md) | 87 | 67 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d68b11e0-f57b-4b65-b616-4bc794db7782) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/toc.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/libraries/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b970895-689e-4533-a3c4-b82fdc8c773f) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/machines/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/machines/index.md) | 84 | 71 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90a669b5-ed9c-48c0-afa4-465f1d9b0216) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/quickref/iqsharp.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/02424ea7cc9374284656dd230e7be74dfe9ad09a/articles/user-guide/quickref/iqsharp.md) | 91 | 56 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80abcdd4-b221-4aab-8172-f0f2d9fe2c10) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Lowest<br>category<br>score | Spelling<br>issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [articles/resources/contributing/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/resources/contributing/index.md) | 86 | 62 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/147ea82f-f88b-49b4-8c01-db3b4064b5f2) | [:white_check_mark:](# "Successfully processed") |
| [articles/resources/contributing/style-guide.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/resources/contributing/style-guide.md) | 81 | 56 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0555e603-0def-4be9-b077-4175954b11bd) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/additional-libraries.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/additional-libraries.md) | 86 | 62 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97d9174c-978c-4f96-8171-b35e5f07d234) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/chemistry/installation.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/chemistry/installation.md) | 80 | 51 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/233e3625-e312-4deb-bf28-9376c55bade6) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/index.md) | 76 | 51 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57e231cf-ed15-4818-93e3-6ba3e89df6c1) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/machine-learning/intro.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/machine-learning/intro.md) | 74 | 50 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4f8b46c-bdda-49af-af00-43247a9ae2e5) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/machine-learning/toc.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/machine-learning/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a0478f2-5766-4b6c-8412-27a00e309ce4) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/numerics/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/numerics/index.md) | 75 | 59 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43bed9a2-2a43-44ef-b9bd-660af0bd3c13) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/numerics/toc.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/numerics/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4340f1e8-792f-4392-8471-56cd656957ee) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/standard/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/standard/algorithms.md) | 74 | 54 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a51df8d-12fe-4f01-9808-b38071d257f3) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/standard/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/standard/index.md) | 87 | 67 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f71799f-f298-438d-89a1-9c06443d6636) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/libraries/toc.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/libraries/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ba99749-7fec-4659-bbc6-2f272b032111) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/machines/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/machines/index.md) | 84 | 71 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/deb81231-4219-4032-8d9f-a9fbbc54586f) | [:white_check_mark:](# "Successfully processed") |
| [articles/user-guide/quickref/iqsharp.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/4c2b866f277d95dd26d5f19c86922a067f947026/articles/user-guide/quickref/iqsharp.md) | 91 | 56 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2998995b-a839-47cb-a370-5907da36dce7) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Pull request closed without merging**
